# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
    packagePath: '$(Build.ArtifactStagingDirectory)/app.zip' 

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(packagePath)'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'haneendevops'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      RESOURCE_GROUP='nodehaneen_group'
      APP_NAME='nodehaneen'

      echo "Fetching Kudu credentials..."
      CREDS=$(az webapp deployment list-publishing-credentials --name $APP_NAME --resource-group $RESOURCE_GROUP --query '[publishingUserName, publishingPassword]' -o tsv)
      USERNAME=$(echo $CREDS | awk '{print $1}')
      PASSWORD=$(echo $CREDS | awk '{print $2}')
      KUDU=https://$APP_NAME.scm.azurewebsites.net

      echo "Deleting lock files..."
      curl -u $USERNAME:$PASSWORD -X DELETE "$KUDU/api/vfs/home/site/locks/status.lock"
      curl -u $USERNAME:$PASSWORD -X DELETE "$KUDU/api/vfs/home/site/locks/hooks.lock"

      echo "Deleting deployments directory..."
      curl -u $USERNAME:$PASSWORD -X DELETE "$KUDU/api/vfs/home/site/deployments/" -H "If-Match: *"

      echo "Restarting App Service..."
      az webapp restart --name $APP_NAME --resource-group $RESOURCE_GROUP 
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'haneendevops'
    appType: 'webAppLinux'
    WebAppName: 'nodehaneen'
    packageForLinux: '$(packagePath)'
    RuntimeStack: 'NODE|20-lts'
