# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
    packagePath: '$(Build.ArtifactStagingDirectory)/app.zip' 

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(packagePath)'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'haneendevops'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      RESOURCE_GROUP='nodehaneen_group'
      APP_NAME='nodehaneen'
      KUDU=https://$APP_NAME.scm.azurewebsites.net
      echo "Fetching Kudu publishing credentials..."
      CREDS=$(az webapp deployment list-publishing-credentials \
          --name $APP_NAME \
          --resource-group $RESOURCE_GROUP \
          --query '{username: publishingUserName, password: publishingPassword}' -o json)
      USERNAME=$(echo $CREDS | jq -r '.username')
      PASSWORD=$(echo $CREDS | jq -r '.password')
      echo "Attempting to delete lock files and deployment folder..."
      for file in status.lock hooks.lock; do
        echo "Deleting /home/site/locks/$file ..."
        curl -s -o /dev/null -w "%{http_code}" -u $USERNAME:$PASSWORD \
          -X DELETE "$KUDU/api/vfs/home/site/locks/$file"
        echo ""
      done
      echo "Deleting /home/site/deployments/ ..."
      HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u $USERNAME:$PASSWORD \
        -X DELETE "$KUDU/api/vfs/home/site/deployments/" -H "If-Match: *")
      if [[ "$HTTP_STATUS" == "200" || "$HTTP_STATUS" == "204" ]]; then
        echo "Successfully deleted /home/site/deployments"
      else
        echo "Failed to delete /home/site/deployments (HTTP $HTTP_STATUS)"
      fi
      echo "Restarting App Service..."
      az webapp restart --name $APP_NAME --resource-group $RESOURCE_GROUP
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'haneendevops'
    appType: 'webAppLinux'
    WebAppName: 'nodehaneen'
    packageForLinux: '$(packagePath)'
    RuntimeStack: 'NODE|20-lts'
